use_frameworks!

platform :ios, '10.0'

target 'KLBlockKVO_Example' do
  pod 'KLBlockKVO', :path => '../'

  target 'KLBlockKVO_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
